### ISSUE TITLE
French thousand separator(nbsp, non-breakable space): can't type numbers in the input if bigger than 1 group

### ISSUE THREAD

**Issue by herickwilke** [JsDaddy/ngx-mask#1229]
# 🐞 bug report

### Description

Hi, I can't type numbers in the input field if the thousand separator is the French non breaking separator (U+202f nor \u00A0) if the number is bigger than one thousand. E.g `5 855`

I can type numbers until the mask inserts the first thousand separator. Than I just can't type more. 

## 🔬 Minimal Reproduction

Stack blitz with the issue example: https://stackblitz.com/edit/stackblitz-starters-7k8fyk?file=src%2Fapp%2Fapp.module.ts

## 🔥 Exception or Error

No exception prompts.

## 🌍 Your Environment

**Angular Version:**
@angular/core": "^16.1.6
"ngx-mask": "^16.2.5"

**Comment by andriikamaldinov1** [comment]
@herickwilke Thanks for using Ngx-mask.
 <input type="text" mask="separator.0" [thousandSeparator]="'  '" [decimalMarker]="','" />

It example all work as expected - https://stackblitz.com/edit/stackblitz-starters-f3zxro?file=src%2Fapp%2Fnumber-input%2Fnumber-input.component.html

**Comment by gpn-autorola** [comment]
Hey @andriikamaldinov1, I ran into the same issue. I changed your supplied stackblitz to properly showcase the bug:

[https://stackblitz.com/edit/stackblitz-starters-jaqnjd4c?file=src%2Fapp%2Fnumber-input%2Fnumber-input.component.html](https://stackblitz.com/edit/stackblitz-starters-jaqnjd4c?file=src%2Fapp%2Fnumber-input%2Fnumber-input.component.html)

Your example uses the char code [32 (SP)](https://www.ascii-code.com/32), but this issue is related to the charcode [160 (NBSP)](https://www.ascii-code.com/CP1252/160). 

Is that something you can and want to support?

**Comment by gpn-autorola** [comment]
I noticed that the non-breaking space mentioned by the bug reporter has a different char code than the one I have mentioned. There's also [8239 (NNBSP)](https://www.fileformat.info/info/unicode/char/202f/index.htm)

Here's a list I found that mentions all possible spaces: https://unicode-explorer.com/articles/space-characters

**Comment by bibullo** [comment]
as @gpn-autorola mentioned this issue still relevant @andriikamaldinov1, should we reopen it?

**Comment by martin-juul** [comment]
Using unicode \u202f doesn't work either
