### ISSUE TITLE
Some patterns are not working properly

### ISSUE THREAD

**Issue by burcalidiagabriela** [JsDaddy/ngx-mask#1370]
# 🐞 bug report

### Is this a regression?
No

### Description
I tried to use the patterns in different combinations and encountered some problems in certain combinations. I described them in a Stackblitz with an example for each combination: https://stackblitz.com/edit/cbohpi-gbgg51?file=src%2Fexample%2Fbutton-overview-example.html

I took the utility of each pattern from here:
https://github.com/JsDaddy/ngx-mask/blob/70c917622c0787a0a9f3ab94274472dcbfcd69c1/projects/ngx-mask-lib/src/lib/ngx-mask.config.ts#L79

## 🔬 Minimal Reproduction
https://stackblitz.com/edit/cbohpi-gbgg51?file=src%2Fexample%2Fbutton-overview-example.html

## 🔥 Exception or Error

<pre><code>
I don't have any errors
</code></pre>

## 🌍 Your Environment

**Angular Version:**
<pre><code>
Angular: 17.0.0
ngx-mask: 16.4.2
</code></pre>

**Comment by andriikamaldinov1** [comment]
You can define custom pattern and specify symbol to be rendered in input field. Patterns may conflict with such letters as h, d, m, s, because we use these characters for dates.
with mask 99-99 - it was bug. 
Thanks for using Ngx-mask. Please update to latest version.
It example all work as expected - https://stackblitz.com/edit/cbohpi-jny4q9?file=package.json
