### ISSUE TITLE
Want to use '*' plain character on a mask but it doesn't seem to work

### ISSUE THREAD

**Issue by davidzamorarey** [JsDaddy/ngx-mask#1466]
# 🐞 bug report

### Is this a regression?

Not sure, just saw the issue trying to use the library

### Description

I have this regular expresion mask variable:

```
  cardNumberMask: (RegExp | string)[] = ['*', '*', '*', '*', ' ', '*', '*', '*', '*', ' ', '*', '*', '*', '*', ' ', /[0-9]/, /[0-9]/, /[0-9]/, /[0-9]/];
```

But when I try to use it the input field shows the label placeholder, not sure why.

The problem is with the '*' character for sure, because if I remove it then it is working.

Do I need to use the specialCharacters option or something like that??

## 🔬 Minimal Reproduction

```
  <input
    [id]="cardNumber"
    [(ngModel)]="internalValue"
    [type]="type"
    [placeholder]="Card Number"
    [mask]="{ mask: ['*', '*', '*', '*', ' ', '*', '*', '*', '*', ' ', '*', '*', '*', '*', ' ', /[0-9]/, /[0-9]/, /[0-9]/, /[0-9]/] }"
    [dropSpecialCharacters]="false"
    [specialCharacters]="['*']"
    />
```

 

## 🔥 Exception or Error

<pre><code>ngx-mask library not working with '*' plain character on mask.
</code></pre>

## 🌍 Your Environment

**Angular Version:**

<pre><code>Angular 16
Node version: v18.20.5
NPM version: 10.8.2
</code></pre>

**Anything else relevant?**

**Comment by andriikamaldinov1** [comment]
@davidzamorarey  Thank you for using Ngx-mask!

Indeed, the * symbol can cause conflicts because it is used to represent an unlimited number of characters in masks. For example, the mask 0* allows the input of an unlimited number of 0 characters.

We have updated the documentation to include a description of this feature.

If you have any further questions or issues, please feel free to open a new issue using the provided template.
