### ISSUE TITLE
Custom patterns not working with AOT compiler

### ISSUE THREAD

**Issue by asp-id** [JsDaddy/ngx-mask#290]
ngx-mask version - **7.3.3**
angular version - **7** 

NgModule configuration
```
     NgxMaskModule.forRoot({
      patterns: {
        'Z': {pattern: new RegExp('\[0-9a-zA-Z\]')}
      }
    })
```

Usage in html template
`<input matInput="" formControlName="applicationNumber" mask="Z{20}"/>`

When compile with `--aot` flag (`ng serve -o --aot`) mask not working. User can not enter any symbols. Unfortunately **AOT** compiler using **by default** for **production mode**, so custom patterns functionality is broken in prod.

**Comment by Thegrep01** [comment]
@asp-id It is an angular limitation, cause aot does not support RegExp in module imports

**Comment by Phantoll** [comment]
as seeing here -> angulartics/angulartics2#339
it's a workarount to write it as string instand of creating a RegExp class instance - thats working for me

**Comment by bpopnikolov** [comment]
Since angular's collector supports only a sub-set of javascript providing a plain object with `RegExp` is not really gonna work. One way around this would be to provide a factory function which returns options object of type `IConfig`. This PR (#447 ) adds a support for factory function which will allow providing `custormPatterns` at root level.

**Comment by NepipenkoIgor** [comment]
@bpopnikolov Thanks . @asp-id @Phantoll you could try latest version. We will publish it today evening

**Comment by xuxicheta** [comment]
Still not working
Here is example https://github.com/xuxicheta/nxg-mask-prod-failure
