### ISSUE TITLE
Percentage mask is no longer working

### ISSUE THREAD

**Issue by lizelleboshoff** [JsDaddy/ngx-mask#498]
Hi
In version 7.9.5 you guys implemented a percentage mask where you could specify the number of decimal places. This was working like a charm.
I've noticed now that with the new version (8.0.0) of the code, it no longer works.  I'm not sure when it stopped working.

This is my code:
<input id="txtPercent" name="txtPercent" #txtPercent="ngModel" type="text" [(ngModel)]="model.Percent" required mask="percent.2" [dropSpecialCharacters]="false" sufix="%"/>

It seems that sufix does not get added when you enter a value.
It also seems that the model value does not get set and the form does not get set to valid. So you cannot submit your form.

Any help would be appreciated.
Thanks

**Comment by ValeriaKochegarova** [comment]
@lizelleboshoff try `<input id="txtPercent" name="txtPercent" #txtPercent="ngModel" type="text" [(ngModel)]="model.Percent" required mask="percent.2" [dropSpecialCharacters]="false" suffix="%"/>` instead of  `<input id="txtPercent" name="txtPercent" #txtPercent="ngModel" type="text" [(ngModel)]="model.Percent" required mask="percent.2" [dropSpecialCharacters]="false" sufix="%"/>`
