### ISSUE TITLE
How to mask something with variable length, e.g. IBAN?

### ISSUE THREAD

**Issue by sl3dg3hamm3r** [JsDaddy/ngx-mask#611]
Hey there

I am struggling to mask patterns with variable lengths, e.g. an [IBAN](https://en.wikipedia.org/wiki/International_Bank_Account_Number). We got there blocks of four, but the overall length does vary (up to 34 alpha numeric characters).

- `BE71 0961 2345 6769` --> length of 16
- `GR96 0810 0010 0000 0123 4567 890` --> length of 27

My naiv approach was to simply use a mask for 34 characters - but this will mark the form control as invalid if less characters are typed in:

`mask="SS00 AAAA 0000 0000 0000 0000 0000 0000 00"` --> not validating if less than 34 chars

Any tips?

**Comment by zauni** [comment]
You can use the 9 instead of 0 for the optional numbers.

So maybe your mask could look like that: `SS00 AAAA 0000 0000 0000 9999 9999 9999 99`

**Comment by sl3dg3hamm3r** [comment]
Sounds good to me. But it behaves buggy, IMHO. See e.g. this [stackblitz](https://stackblitz.com/edit/angular-vadkpv), I can't enter the last digit as defined in the second field...

**Comment by lgaida** [comment]
I have also stumbled across this. The stackblitz-link @sl3dg3hamm3r posted recreates the issue perfectly.

The following workaround may give an idea on how you can create a workaround until this issue receives further investigation.
I created a custom maskpattern which allows alphanumeric-characters (since an IBAN can consist of alphanumerics)
```
const maskConfig: Partial<IConfig> = {
  patterns: {
  //....
    C: {
      pattern: new RegExp('[a-zA-Z0-9]'),
    }
  //....
  }
}
```
used the custom pattern and deactivated validation on the input
```
 <input [formControlName]="formControlNames.iban" matInput type="text"
 mask="SS00 CCCC CCCC CCCC CCCC CCCC CCCC CCCC CC" [validation]="false" required/>
```
applied a `Validators.minLength(15)` in my _iban-input-containing-component.ts_, since the [shortest IBAN-Format](https://en.wikipedia.org/wiki/International_Bank_Account_Number#IBAN_formats_by_country) currently known has 15 characters.

An input like this:
- forces 2 letters, followed by 2 digits, and atleast 13 other alphanumeric characters
- validates correctly because of the minLength validator
- does not corrupt character spacing

**Comment by beradrian** [comment]
I had something similar with duration in hours and minutes and I managed to do it like this `0:m0||00:m0||000:m0` but it's not working smoothly
