### ISSUE TITLE
Mask with optional digits skips input character

### ISSUE THREAD

**Issue by ccosmincc** [JsDaddy/ngx-mask#648]
Given the following mask for a credit card which should contain 12 to 19 characters, first 12 being mandatory and the rest optional, grouped in 4 character groups, when trying to type the first character of the last optional group, it is skipped, being replaced with a space character.

Steps to reproduce:

mask="0000 0000 0000 9999 9999"
input: 1234 1234 1234 1234 1234
output: 1234 1234 1234 1234 234
expected output: 1234 1234 1234 1234 1234

**Comment by WESquad-spires** [comment]
Have the exact same issue on trying to validate an IBAN.

Tested on Angular 11.0.5 with a reactive form.

mask="SS00 AAAA 0000 0000 0000 0000 9999 9999 99"
input="FR12345678901234567890123456789012"
output="FR12 3456 7890 1234 5678 9012 3456  890  2"
expected output=""FR12 3456 7890 1234 5678 9012 3456 7890 12"

Also, issue does not happen when pasting value inside the input instead of typing it.

**Comment by GlebChiz** [comment]
@SlippySken We took this issue in work. We will have fixed this issue in some days.

**Comment by NepipenkoIgor** [comment]
@ccosmincc  @WESquad-spires  @SlippySken  Hi all . Thank you that using ngx-mask. Please try version >= 13.1.15
