### ISSUE TITLE
Any plans on supporting Angular Reactive Forms?

### ISSUE THREAD

**Issue by diegosiao** [JsDaddy/ngx-mask#710]
It seems like the Angular Reactive Forms are not "officially" supported... Is there any plans to support it in near future?

**Comment by ColinMorris83** [comment]
Can you provide bit more info on what is unsupported?

**Comment by florindr** [comment]
sorry if this is slightly off topic but i find that masking a reactive form input changes the form's value. is this the expected behaviour? I have a peculiar use case for a 'read-only mask' where a value may be 10.12345 and we only show 2dp (separator.2) but when user edits the value it should expand to all percentage points (up to 10)

`  onBlur() {
    console.log('v-before-blur='+this.group.controls['anInput'].value);
    this.mask = 'separator.2';

  }

  onFocus() {
    console.log('v-before-focus='+this.group.controls['anInput'].value);
    this.mask = 'separator.10';
  }`

the problem is when saving the value back, the reactive form will keep only the 2dp whereas i'd expect the full original value.

**Comment by NepipenkoIgor** [comment]
@florindr Thank you that using our package. Ngx-mask package works for both template driven and reactive forms in same way. If you steel have issue please create new issues from template . If it is a question please use stackoverflow with ngx-mask tag
