### ISSUE TITLE
clearIfNotMatch declare default value

### ISSUE THREAD

**Issue by mhubertm** [JsDaddy/ngx-mask#821]
**clearIfNotMatch** the default "clear" value is empty string instead of null

**Comment by NepipenkoIgor** [comment]
@mhubertm Thank you that using our package. It seems like right behaviour  because for empty input field default value is empty string. But If you think that issue a bug or feature please create new issues from template . If it is a question please use stackoverflow with ngx-mask tag

**Comment by dexluce** [comment]
Hello,

I think having NULL instead of zero or an empty string has a few use case.
I fact, zero or empty string can be valid values after all. For my current project, I use your great package to display money amount input. In this case, an amount of zero is a valid value, and is used by the backend for calculation.
In this context, having a zero when I clear the input is an issue.

regards
