### ISSUE TITLE
Caret position displacement

### ISSUE THREAD

**Issue by andrei-varchanka** [JsDaddy/ngx-mask#861]
Thousand separator issue:
If I what to change the first digit and this digit is only one in triplet 
then caret the carriage moves to the right, to the last digit after I deleted the first digit
![image](https://user-images.githubusercontent.com/53002740/105702383-c4c68680-5f1c-11eb-830e-91ffb4637859.png)

![image](https://user-images.githubusercontent.com/53002740/105702853-6f3ea980-5f1d-11eb-8056-f476ea01929b.png)

ER: caret stays where it was, like for digit changing in the middle of number
![image](https://user-images.githubusercontent.com/53002740/105703005-aa40dd00-5f1d-11eb-8ded-d36e62fb9b32.png)

**Comment by andrei-varchanka** [comment]
it seems that issue duplicates https://github.com/JsDaddy/ngx-mask/issues/844

**Comment by NepipenkoIgor** [comment]
@andrei-varchanka  Hi. Thank you for using our package. Please try v12.0.0

**Comment by jupitel1993** [comment]
@NepipenkoIgor Hi, just have tried v12.0.0
![image](https://user-images.githubusercontent.com/15675457/120329827-e7b2de00-c2f4-11eb-837d-2c895483d277.png)
clicking [Delete] once leads to
![image](https://user-images.githubusercontent.com/15675457/120329944-01ecbc00-c2f5-11eb-9ff2-1e3b5b0093bb.png)

looks like it is not expected behavior
